name: tmi
description: Dart library for the Twitch Messaging Interface. (Twitch.tv)
version: 0.1.0
author: Alan Chen <alanchen1908@gmail.com>
homepage: https://github.com/alanqchen/tmi.dart
repository: https://github.com/alanqchen/tmi.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  eventify: ^1.0.0
  logger: ^1.0.0
  http: ^0.13.1
  quiver: ^3.0.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  test_cov: ^1.0.1
  build_runner: ^1.11.0
  test:
  mockito: ^5.0.5


