name: Code Coverage
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
     
    container:
      image:  google/dart:latest
     
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Code Coverage
      run: pub run test_cov
    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v1.4.1
      with:
        token: ${{secrets.CODECOV_UPLOAD_TOKEN}}
        file: coverage/lcov.info
